2022-02-04 11:45:36 info: ---------------------------------------
2022-02-04 11:45:36 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-02-04 11:45:36 info: ---------------------------------------
2022-02-04 11:45:38 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()`
    ✕ should take a single argument (2 ms)
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument
    ✓ should resolve when called with a string argument (1 ms)
    ✓ should reject with an Error object when called without an argument (1 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● getAnonName › should take a single argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 2

      58 |
      59 |   test('should take a single argument', () => {
    > 60 |     expect(state.paramCount).toBe(1);
         |                              ^
      61 |   });
      62 |
      63 |   test('`resolve()` should be called with a one argument', () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:60:30)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 7 passed, 9 total
Snapshots:   0 total
Time:        0.872 s, estimated 1 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-02-04 11:45:39 error: *** ESLint Report ***

ex1-johnWho.js
  12:33  error  'callback' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-02-04 11:47:17 info: ---------------------------------------
2022-02-04 11:47:17 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-02-04 11:47:17 info: ---------------------------------------
2022-02-04 11:47:19 info: All unit tests passed.
2022-02-04 11:47:20 info: All steps were completed successfully
2022-02-04 12:47:33 info: -------------------------------------------------
2022-02-04 12:47:33 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-02-04 12:47:33 info: -------------------------------------------------
2022-02-04 12:47:37 info: All unit tests passed.
2022-02-04 12:47:40 info: All steps were completed successfully
2022-02-04 02:58:02 info: ---------------------------------------
2022-02-04 02:58:02 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-02-04 02:58:02 info: ---------------------------------------
2022-02-04 02:58:06 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDie.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js
  rollDie
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ should call `new Promise()`
    ✓ `resolve()` should be called with a one argument (1 ms)
    ✓ `reject()` should be called with a one argument
    ✓ should resolve when the die settles successfully (1 ms)
    ✓ should reject with an Error when the die rolls off the table (1 ms)

  ● rollDie › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        0.909 s, estimated 1 s
Ran all test suites matching /ex3-rollDie.test.js/i.
2022-02-04 02:58:07 error: *** ESLint Report ***

ex3-rollDie.js
  3:9  error  'reject' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-02-04 03:00:33 info: ---------------------------------------
2022-02-04 03:00:33 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-02-04 03:00:33 info: ---------------------------------------
2022-02-04 03:00:35 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDie.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js
  rollDie
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ should call `new Promise()`
    ✓ `resolve()` should be called with a one argument (1 ms)
    ✓ `reject()` should be called with a one argument
    ✓ should resolve when the die settles successfully (2 ms)
    ✓ should reject with an Error when the die rolls off the table (1 ms)

  ● rollDie › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        0.612 s, estimated 1 s
Ran all test suites matching /ex3-rollDie.test.js/i.
2022-02-04 03:01:10 info: ---------------------------------------
2022-02-04 03:01:10 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-02-04 03:01:10 info: ---------------------------------------
2022-02-04 03:01:12 info: All unit tests passed.
2022-02-04 03:01:14 info: All steps were completed successfully
2022-02-04 03:55:01 info: ---------------------------------------
2022-02-04 03:55:01 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-02-04 03:55:01 info: ---------------------------------------
2022-02-04 03:55:05 info: All unit tests passed.
2022-02-04 03:55:08 info: All steps were completed successfully
2022-02-04 04:38:57 info: --------------------------------------------
2022-02-04 04:38:57 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-02-04 04:38:57 info: --------------------------------------------
2022-02-04 04:39:01 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    ✓ should exist and be executable (1 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ `rollDice` should not contain unneeded console.log calls (1 ms)
    ✓ should use `dice.map()` (1 ms)
    ✓ should use `Promise.all()`
    ✓ should resolve when all dice settle successfully (1 ms)
    ✕ should reject with an Error when a die rolls off the table

  ● ex4-pokerDiceAll › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● ex4-pokerDiceAll › should reject with an Error when a die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      63 |
      64 |   test('should reject with an Error when a die rolls off the table', async () => {
    > 65 |     expect.assertions(3);
         |            ^
      66 |     expect(exported).toBeDefined();
      67 |
      68 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:65:12)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 5 passed, 7 total
Snapshots:   0 total
Time:        0.977 s, estimated 1 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.
(node:26220) UnhandledPromiseRejectionWarning: Error: Die 1 rolled off the table.

(Use `node --trace-warnings ...` to show where the warning was created)
(node:26220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:26220) UnhandledPromiseRejectionWarning: Error: Die 2 rolled off the table.

(node:26220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:26220) UnhandledPromiseRejectionWarning: Error: Die 3 rolled off the table.

(node:26220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:26220) UnhandledPromiseRejectionWarning: Error: Die 4 rolled off the table.

(node:26220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:26220) UnhandledPromiseRejectionWarning: Error: Die 5 rolled off the table.

(node:26220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
2022-02-05 11:01:31 info: --------------------------------------------
2022-02-05 11:01:31 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-02-05 11:01:31 info: --------------------------------------------
2022-02-05 11:01:35 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    ✓ should exist and be executable (1 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ `rollDice` should not contain unneeded console.log calls (1 ms)
    ✓ should use `dice.map()`
    ✓ should use `Promise.all()`
    ✕ should resolve when all dice settle successfully (2 ms)
    ✓ should reject with an Error when a die rolls off the table (1 ms)

  ● ex4-pokerDiceAll › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● ex4-pokerDiceAll › should resolve when all dice settle successfully

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise
    Received constructor: Array

      52 |
      53 |     const promise = rollDice();
    > 54 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      55 |     const result = await promise;
      56 |     expect(Array.isArray(result)).toBe(true);
      57 |     expect(result).toHaveLength(5);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:54:21)

  ● ex4-pokerDiceAll › should resolve when all dice settle successfully

    expect.assertions(4)

    Expected four assertions to be called but received two assertion calls.

      46 |
      47 |   test('should resolve when all dice settle successfully', async () => {
    > 48 |     expect.assertions(4);
         |            ^
      49 |     expect(exported).toBeDefined();
      50 |
      51 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:48:12)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 5 passed, 7 total
Snapshots:   0 total
Time:        0.888 s, estimated 1 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.
(node:27683) UnhandledPromiseRejectionWarning: Error: Die 1 rolled off the table.

(Use `node --trace-warnings ...` to show where the warning was created)
(node:27683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:27683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27683) UnhandledPromiseRejectionWarning: Error: Die 2 rolled off the table.

(node:27683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:27683) UnhandledPromiseRejectionWarning: Error: Die 3 rolled off the table.

(node:27683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:27683) UnhandledPromiseRejectionWarning: Error: Die 4 rolled off the table.

(node:27683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:27683) UnhandledPromiseRejectionWarning: Error: Die 5 rolled off the table.

(node:27683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
2022-02-05 11:01:37 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  37:3  warning  Remove commented-out code  hyf/no-commented-out-code

✖ 1 problem (0 errors, 1 warning)


2022-02-05 11:03:29 info: --------------------------------------------
2022-02-05 11:03:29 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-02-05 11:03:29 info: --------------------------------------------
2022-02-05 11:03:32 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    ✓ should exist and be executable (1 ms)
    ✓ should have all TODO comments removed
    ✓ `rollDice` should not contain unneeded console.log calls (1 ms)
    ✓ should use `dice.map()` (1 ms)
    ✓ should use `Promise.all()`
    ✕ should resolve when all dice settle successfully (2 ms)
    ✓ should reject with an Error when a die rolls off the table (1 ms)

  ● ex4-pokerDiceAll › should resolve when all dice settle successfully

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise
    Received constructor: Array

      52 |
      53 |     const promise = rollDice();
    > 54 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      55 |     const result = await promise;
      56 |     expect(Array.isArray(result)).toBe(true);
      57 |     expect(result).toHaveLength(5);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:54:21)

  ● ex4-pokerDiceAll › should resolve when all dice settle successfully

    expect.assertions(4)

    Expected four assertions to be called but received two assertion calls.

      46 |
      47 |   test('should resolve when all dice settle successfully', async () => {
    > 48 |     expect.assertions(4);
         |            ^
      49 |     expect(exported).toBeDefined();
      50 |
      51 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:48:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        0.553 s, estimated 1 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.
(node:27802) UnhandledPromiseRejectionWarning: Error: Die 1 rolled off the table.

(Use `node --trace-warnings ...` to show where the warning was created)
(node:27802) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:27802) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27802) UnhandledPromiseRejectionWarning: Error: Die 2 rolled off the table.

(node:27802) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:27802) UnhandledPromiseRejectionWarning: Error: Die 3 rolled off the table.

(node:27802) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:27802) UnhandledPromiseRejectionWarning: Error: Die 4 rolled off the table.

(node:27802) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:27802) UnhandledPromiseRejectionWarning: Error: Die 5 rolled off the table.

(node:27802) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
2022-02-05 11:03:32 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  36:3  warning  Remove commented-out code  hyf/no-commented-out-code

✖ 1 problem (0 errors, 1 warning)


2022-02-05 11:10:09 info: --------------------------------------------
2022-02-05 11:10:09 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-02-05 11:10:09 info: --------------------------------------------
2022-02-05 11:10:13 info: All unit tests passed.
2022-02-05 11:10:16 info: All steps were completed successfully
2022-02-05 11:12:21 info: --------------------------------------------
2022-02-05 11:12:21 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-02-05 11:12:21 info: --------------------------------------------
2022-02-05 11:12:23 info: All unit tests passed.
2022-02-05 11:12:25 info: All steps were completed successfully
2022-02-05 11:38:53 info: ----------------------------------------------
2022-02-05 11:38:53 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2022-02-05 11:38:53 info: ----------------------------------------------
2022-02-05 11:38:57 info: All unit tests passed.
2022-02-05 11:39:00 info: All steps were completed successfully
2022-02-05 11:42:33 info: ----------------------------------------------
2022-02-05 11:42:33 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2022-02-05 11:42:33 info: ----------------------------------------------
2022-02-05 11:42:35 info: All unit tests passed.
2022-02-05 11:42:36 info: All steps were completed successfully
2022-02-05 11:46:09 info: ---------------------------------------
2022-02-05 11:46:09 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-02-05 11:46:09 info: ---------------------------------------
2022-02-05 11:46:12 info: All unit tests passed.
2022-02-05 11:46:15 info: All steps were completed successfully
2022-02-05 11:46:35 info: -------------------------------------------------
2022-02-05 11:46:35 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-02-05 11:46:35 info: -------------------------------------------------
2022-02-05 11:46:36 info: All unit tests passed.
2022-02-05 11:46:38 info: All steps were completed successfully
2022-02-05 11:46:53 info: ---------------------------------------
2022-02-05 11:46:53 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-02-05 11:46:53 info: ---------------------------------------
2022-02-05 11:46:55 info: All unit tests passed.
2022-02-05 11:46:56 info: All steps were completed successfully
2022-02-05 11:47:07 info: --------------------------------------------
2022-02-05 11:47:07 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-02-05 11:47:07 info: --------------------------------------------
2022-02-05 11:47:09 info: All unit tests passed.
2022-02-05 11:47:11 info: All steps were completed successfully
2022-02-05 11:47:23 info: ----------------------------------------------
2022-02-05 11:47:23 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2022-02-05 11:47:23 info: ----------------------------------------------
2022-02-05 11:47:25 info: All unit tests passed.
2022-02-05 11:47:26 info: All steps were completed successfully
